name: Deploy Donor App
on:
  push:
    branches: [ "main" ]  # Trigger on main branch pushes

permissions:
  contents: write  # Required to upload files
  pages: write     # Needed for GitHub Pages
  id-token: write  # Required for authentication

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Create config.js with your secrets
      - name: Setup config
        run: |
          echo "window.CONFIG = {
            DONOR_ID: '${{ secrets.DONOR_ID }}',
            JSONBIN_KEY: '${{ secrets.JSONBIN_KEY }}'
          }" > config.js

          # Verify file creation (debug)
          echo "Config file created at:"
          ls -la config.js
          echo "First 2 lines:"
          head -n 2 config.js

      # 3. Debug: List all files (optional)
      - name: Verify files
        run: |
          echo "Repository contents:"
          find . -type f -not -path './.git/*'

      # 4. Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Auto-provided by GitHub
          publish_dir: ./  # Deploy everything
          keep_files: false  # Clean old files
          enable_jekyll: false  # Disable Jekyll processing

      # 5. Post-deployment verification
      - name: Verify deployment
        run: |
          echo "Deployment complete!"
          echo "Visit: https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}/"
