name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

# Add this permissions block
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup config
        run: |
          echo "window.CONFIG = {
            DONOR_BIN: '${{ secrets.JSONBIN_BIN_ID }}',
            JSONBIN_KEY: '${{ secrets.JSONBIN_API_KEY }}'
          }" > config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
