name: Deploy with Config
on:
  push:
    branches: [ "main" ]  # Runs on pushes to main branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      # Create config.js with secrets
      - name: Setup config
        run: |
          echo "window.CONFIG = {
            DONOR_ID: '${{ secrets.DONOR_ID }}',
            JSONBIN_KEY: '${{ secrets.JSONBIN_KEY }}'
          }" > config.js

      # Optional: Verify config was created
      - name: Debug
        run: cat config.js  # Prints config (keys masked in logs)

      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
